**Class 1** Solve for the algorithm.

In [18]:
gamma0=[1.0 0.0 0.0]
crit=1.0
tol=1e-8
P=[0.8 0.1 0.1; 0.4 0.3 0.3; 0.2 0.4 0.4]

iter=0
maxiter=10_000
while crit>tol && (iter<maxiter)
    iter +=1
    gamma1=gamma0 *P
    crit= maximum(abs.(gamma1-gamma0))
    gamma0=copy(gamma1)
end 

s=[0.4 1.0 1.8]

L= gamma0 * s'

1×1 Matrix{Float64}:
 0.7999999940395368

**2.Exercise*** 
We move now to a more complicated problem. Now we have two dimensions of heterogeneity, alpha and s. Then we use a slightly different method to build the markovian chain.

In [21]:
M= [0.0 0.2; 0.1 0.4;0.3 0.8]
M_2= [0.0;0.1;0.3]
Grid_a=[0.0 0.5 1]

s=[1 2]

L= zeros(3,3)

#first need to generate the matrix that will store the results. Suppose we want to implement only a 3 by three matrix

for i in 1:3
    for j in 1:3
        if M_2[i]

        L[i,j]= M_2[i]- 

    end    
end    


    

3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [5]:
##let's start by a very simple case, where i want to automatize a function for the first situation. I need to use functions integrated in Julia to do this efficiently.
M_2= [0.0, 0.1, 0.3]
Grid_a=[0.0, 0.5, 1]

pi= zeros(length(Grid_a), length(M_2))

ixs= searchsortedlast.(Ref(Grid_a), M_2)
interval=clamp.(ixs, 1, length(Grid_a)-1)

a0=Grid_a[interval]
a1=Grid_a[interval.+1]

for j in 1:length(M_2)
    w_right= (M_2[j]-a0[j])/(a1[j] - a0[j])
    w_left= 1-w_right

    pi[j, interval[j]]= w_left
    pi[j, interval[j]+1]= w_right

end 

pi



 









3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.8  0.2  0.0
 0.4  0.6  0.0

In [ ]:
##full fledge code

M_2= [0.0 0.1 0.3; 0.2 0.4 0.8]
Grid_a=[0.0, 0.5, 1]

pi= zeros(length(Grid_a), size(M_2,2), size(M_2,1))

for s in 1:2 
    ixs= searchsortedlast.(Ref(Grid_a), M_2[s, :])
    interval=clamp.(ixs, 1, length(Grid_a)-1)

    a0=Grid_a[interval]
    a1=Grid_a[interval.+1]

    for j in 1:size(M_2,2)
    w_right= (M_2[s,j]-a0[j])/(a1[j] - a0[j])
    w_left= 1-w_right

    pi[j, interval[j], s]= w_left
    pi[j, interval[j]+1, s]= w_right
    end 
end 

A = pi[:, :, 1]   
B = pi[:, :, 2]   
pi

#done!


**Class 2** 