**REPLICATION CODE: MOURIFIÉ/HENRY/MEANGO**

Start date: 10/11/2025
Author: Jordi Torres Vallverdú

Goal: idea is to replicate the analysis done by Mourifié et al (2020) in another context with another data. The idea is to seek new applications of their methodology.

Notes on the context: I am using data on Belgium region of Flandes in the 1990s. I have a panel of students observed from the beginning of high-school up to two years into higher education. Given that I don't observe future labor outcomes, I will only consider potential outcomes in terms of success probability of having completed the first year of higher education (this is a proxy for completion)


$D=\{1,0\}$, where 1 is entered stem high school track and 0 if entered non-stem high-school track

$Y=\{1,0\}$, where 1 is graduated from stem degree and 0 is graduated from non-stem degree

Z, set of instruments


In [18]:
using StatFiles, DataFrames

data_path = "/Users/jorditorresvallverdu/Library/Mobile Documents/com~apple~CloudDocs/tse/year1/papers_final_memoire/data/clean/roymodel_database.dta"

export_dir = "/Users/jorditorresvallverdu/Documents/GitHub/TSE-2025-2026/set_identification/"


main = DataFrame(load(data_path))

2206×54 DataFrame
  Row │ ID      hs_course1  hs_stem1  postsec_type2  postsec_stem2  c_par_beli ⋯
      │ Int32?  Float32?    Float32?  Float32?       Float32?       Int32?     ⋯
──────┼─────────────────────────────────────────────────────────────────────────
    1 │  11135         6.0       1.0            2.0            0.0             ⋯
    2 │  11137         6.0       0.0            2.0            0.0
    3 │  11154         6.0       1.0            1.0            0.0            
    4 │  11161         6.0       1.0            1.0            0.0
    5 │  11162         6.0       1.0            1.0            0.0             ⋯
    6 │  11163         6.0       1.0            2.0            0.0
    7 │  11166         6.0       1.0            2.0            0.0
    8 │  11171         6.0       0.0            1.0            0.0
  ⋮   │   ⋮         ⋮          ⋮            ⋮              ⋮                 ⋮ ⋱
 2200 │  43127         6.0       1.0            1.0            0.0             ⋯
 2201 │  43132         6.0       0.0            2.0            0.0
 2202 │  43144         4.0       0.0            2.0            0.0
 2203 │  43145         4.0       0.0            2.0            0.0
 2204 │  43151         6.0       0.0            2.0            0.0             ⋯
 2205 │  43155         6.0       1.0            2.0            0.0
 2206 │  43157         6.0       1.0            1.0            1.0
                                                49 columns and 2191 rows omitted

**1. Data manipulation**

First we create a subsample of observations on gender and socio-economic status, just like they do in their exercise. I will create bins based on this: 

- Gender
- Income categories: 6 brackets
- Minority status (proxied by family background)


In [2]:
using DataFramesMeta, Statistics 

groups = groupby(main, [:c_sskills_income, :c_iq_male])
subsamples = [DataFrame(g) for g in groups]


10-element Vector{DataFrame}:
 308×53 DataFrame
 Row │ ID      hs_course1  hs_stem1  postsec_type2  postsec_stem2  c_par_belie ⋯
     │ Int32?  Float32?    Float32?  Float32?       Float32?       Int32?      ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │  11166         6.0       1.0            2.0            0.0              ⋯
   2 │  11246         6.0       0.0            1.0            0.0
   3 │  11272         6.0       1.0            2.0            0.0
   4 │  11311         6.0       1.0            2.0            0.0
   5 │  11457         6.0       0.0            2.0            0.0              ⋯
   6 │  11473         6.0       0.0            2.0            0.0
   7 │  12652         6.0       0.0            2.0            1.0
   8 │  12666         4.0       0.0            2.0            0.0             
  ⋮  │   ⋮         ⋮          ⋮            ⋮              ⋮                 ⋮  ⋱
 302 │  42322         4.0       0.0            2.0       

**2. Test for monothonicity of E(Y/Z=z)**
This boils down to testing whether the probability of Y=1 is increasing in Z. Usual tests include Hu, Shi (2019), Chetverikhov (2013). These tests, however, are done under much more complicated cases as in mine: Hu et al, for example, account for a setting with Y being continuous and Z also being continuous; in my case, I just need to test over Z=1,2,3...

Given that the idea is to use set identification techniques, I will provide some evidence that this holds or not for a given subset of the data. Then I will focus mostly on the el(z) measure. 

In [19]:
size_subsample=10
size_p=3

m= zeros(Float64, size_subsample, size_p, size_p)

10×3×3 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [21]:
##Estimate probabilities 
zvals = sort(unique(main.c_iq_opl))

function cell_probs(df)
    k= length(zvals)
    p_k= zeros(Float64, k)
    n_k= zeros(Int, k)
    for z in zvals
        num = sum((df.postsec_stem2 .== 1) .& (df.c_iq_opl .== z))
        n_k[z] = sum(df.c_iq_opl .== z)
        p_k[z] = num / n_k[z]
    end

    return p_k, n_k
end


probs= [cell_probs(i) for i in subsamples]

10-element Vector{Tuple{Vector{Float64}, Vector{Int64}}}:
 ([0.2636363636363636, 0.3888888888888889, 0.4444444444444444], [110, 108, 90])
 ([0.5365853658536586, 0.6075949367088608, 0.5462962962962963], [82, 79, 108])
 ([0.25, 0.2463768115942029, 0.41025641025641024], [124, 69, 39])
 ([0.5909090909090909, 0.5526315789473685, 0.7368421052631579], [66, 38, 19])
 ([0.24, 0.38095238095238093, 0.3023255813953488], [75, 126, 86])
 ([0.5964912280701754, 0.5633802816901409, 0.6727272727272727], [57, 71, 55])
 ([0.2222222222222222, 0.30434782608695654, 0.3221476510067114], [18, 69, 149])
 ([0.5714285714285714, 0.5217391304347826, 0.5412844036697247], [7, 46, 109])
 ([0.16666666666666666, 0.26666666666666666, 0.3791469194312796], [6, 30, 211])
 ([0.75, 0.4666666666666667, 0.5571428571428572], [4, 15, 140])

In [5]:
#Estimate test

function pav3(pk, nk)
    p1, p2, p3 = pk
    n1, n2, n3 = nk

  #monothonicity holds
  if p1 ≤ p2 ≤ p3
    return pk
  end


  #case 1
  if p1>=p2
    
    θ_12= (p1*n1 + p2*n2)/(n1+n2)

    if p3>=θ_12
      return[θ_12, θ_12, p3]
    else 
    θ_123= (p1*n1 + p2*n2 + p3*n3)/(n1+n2+n3)

    return[θ_123,θ_123,θ_123]
    end 
  end 
  
  #case 2
  if p2>=p3

    θ_23= (p2*n2 + p3*n3)/(n2+n3)

    if p1<θ_23
      return[p1, θ_23, θ_23]
    else 
      θ_123= (p1*n1 + p2*n2 + p3*n3)/(n1+n2+n3)
     return[θ_123,θ_123,θ_123]
    end 

  end 


end


pav3 (generic function with 1 method)

In [6]:
#To check it works: 

pk = [0.40, 0.20, 0.50]
nk = [50, 60, 40]

pav3(pk, nk)


3-element Vector{Float64}:
 0.2909090909090909
 0.2909090909090909
 0.5

In [7]:
p_hat= zeros(length(subsamples), length(zvals))

for i in 1:length(subsamples)

    pk, nk = probs[i]

    p_hat[i,:]= pav3(pk,nk)
end 

p_hat

10×3 Matrix{Float64}:
 0.263636  0.388889  0.444444
 0.536585  0.572193  0.572193
 0.248705  0.248705  0.410256
 0.576923  0.576923  0.736842
 0.24      0.349057  0.349057
 0.578125  0.578125  0.672727
 0.222222  0.304348  0.322148
 0.528302  0.528302  0.541284
 0.166667  0.266667  0.379147
 0.526316  0.526316  0.557143

In [8]:
n=zeros(length(subsamples))
T=zeros(length(subsamples))
[n[i]= nrow(subsamples[i]) for i in 1:length(subsamples)]

for i in 1:length(subsamples)

    pk, nk= probs[i]
    p_hat[i,:]= pav3(pk,nk)

    T[i]= sqrt(n[i])* maximum(pk .- p_hat[i,:])
end

T

10-element Vector{Float64}:
 0.0
 0.5806429148558914
 0.019729982139543877
 0.1551123986910417
 0.5403487325125411
 0.24845372815718206
 0.0
 0.5489130808132765
 0.0
 2.8205505739422945

In [9]:
for i in 1:length(subsamples)
    println((i, unique(subsamples[i].c_sskills_income), unique(subsamples[i].c_iq_male), T[i]))
end


(1, Union{Missing, Float32}[1.0], Union{Missing, Int8}[0], 0.0)
(2, Union{Missing, Float32}[1.0], Union{Missing, Int8}[1], 0.5806429148558914)
(3, Union{Missing, Float32}[2.0], Union{Missing, Int8}[0], 0.019729982139543877)
(4, Union{Missing, Float32}[2.0], Union{Missing, Int8}[1], 0.1551123986910417)
(5, Union{Missing, Float32}[3.0], Union{Missing, Int8}[0], 0.5403487325125411)
(6, Union{Missing, Float32}[3.0], Union{Missing, Int8}[1], 0.24845372815718206)
(7, Union{Missing, Float32}[4.0], Union{Missing, Int8}[0], 0.0)
(8, Union{Missing, Float32}[4.0], Union{Missing, Int8}[1], 0.5489130808132765)
(9, Union{Missing, Float32}[5.0], Union{Missing, Int8}[0], 0.0)
(10, Union{Missing, Float32}[5.0], Union{Missing, Int8}[1], 2.8205505739422945)


In [10]:
using Distributions
using Random
Random.seed!(12345)   #seed


b_iter= 1000 # bootstrap

T_dist= zeros(length(subsamples), b_iter)

##set seed!!!

for b in 1:b_iter
  for i in 1:length(subsamples)

        dt = subsamples[i]   ##then we loop over i 
        p_iso = p_hat[i,:]   
        Z = dt.c_iq_opl  
        p_obs = p_iso[Z]   
        Y_b = rand.(Bernoulli.(p_obs))

        dt_boot = deepcopy(dt)       
        dt_boot.postsec_stem2 = Y_b   #simul replace

        pk_b, nk_b= cell_probs(dt_boot)
        p_iso_b= pav3(pk_b,nk_b)
        T_dist[i,b]= sqrt(n[i])* maximum(pk_b .- p_iso_b)
  end 
  
end

T_dist





10×1000 Matrix{Float64}:
 0.162499   0.0       0.0        0.0        …  0.0       0.0        0.0
 0.636154   0.908157  0.174304   0.0           0.0       0.802686   0.443511
 0.0        0.0       0.0        0.042923      0.0       0.152112   0.0
 0.0775562  0.0       0.0        0.0646302     0.0       0.0972854  0.384549
 0.0        0.0       0.0241001  0.0           0.0       0.100206   0.0393212
 0.220642   0.338486  0.132282   0.0332674  …  0.0       0.0        0.068047
 0.0        0.0       0.0        0.0           1.01981   1.52377    0.0
 0.0        0.603371  1.0443     0.706908      3.76001   0.752002   2.36719
 0.0        0.0       0.545612   0.0           0.873124  0.0        1.30969
 3.48421    0.0       2.82019    5.97293       2.82055   0.331829   0.331829

In [11]:
using Statistics

c_value_95= zeros(length(subsamples))
c_value_90= zeros(length(subsamples))

[c_value_95[i]= quantile(T_dist[:, i], 0.95) for i in 1:length(subsamples)]
[c_value_90[i]= quantile(T_dist[:, i], 0.90) for i in 1:length(subsamples)]



10-element Vector{Float64}:
 0.9209592920493659
 0.6338498668084624
 1.221886272359745
 1.233510653554208
 0.932791136162614
 0.5736736238725959
 1.1608794377064289
 1.7906664615777967
 1.308065870576294
 1.038874319277513

In [12]:
t_result95= zeros(length(subsamples))
t_result90= zeros(length(subsamples))

for i in 1:length(subsamples)
    if (T[i]>=c_value_95[i])
        t_result95[i]=1
    else 
        t_result95[i]=0
    end

    if (T[i]>=c_value_90[i])
        t_result90[i]=1
    else 
        t_result90[i]=0
    end


end 

t_result95

10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 1.0

**Using IQ as instrument**-->classic Manski Pepper type of instrument






**2. Estimating bounds on the L(z) measure**

The goal is now to understand what explains the violations of Roy selection model using the same method as in Mourifié, Henry, Meango (2020). Will keep the same example going, but, if needed, I will also include a continuous instrument: example can be numeric IQ estimated at baseline. 

The main issue with this literature is that sample analogs of $\Theta_I$ are the suprema and infima of estimated bounding functions and they have substantial finite sample bias and estimated bounds tend to be much tighter than population bounds. -->Manski/Pepper (2001).

I think I need to treat the instrument as continuous; if not it is meaningless. Because CRL seems to be devised with this property. Then I probably need to adapt the test for monothonicity too. But so far, I have something, which is fine.

Start simple; support is discrete; then we do the same exercise with a continuous instrument. 